### ISSUE TITLE
Over- en onderbewoonde woningen

### ISSUE THREAD

**Issue by VirgeSmetsStadAntwerpen** [provinciesincijfers/kadaster-post-processing#19]
woongelegenheden: kadaster en rijksregister: https://provincies.incijfers.be/databank?workspace_guid=cc2406a5-e6e2-487b-ac63-3f3b95fb8d0c
zinvol om het aantal onbewoonde woningen hieruit te halen

**Comment by joostschouppe** [comment]
[Je kan die eenvoudig uit de kubus halen](https://provincies.incijfers.be/databank?workspace_guid=391bf59b-bc03-4b94-8989-8c86f567a5e5). Maar we publiceren dit bewust niet als afzonderlijk onderwerp, omdat het te moeilijk te duiden is:
- om allerlei redenen kan het zijn dat het wel bewoond is maar er niemand gedomicileerd is (vb studentenhuisvesting, of mensen die om allerlei redenen zich niet gedomicilieerd hebben op het pand)
- het omvat ook tweede woningen en private panden die als vakantiewoning verhuurd worden
- het kan zijn dat we de bewoning onterecht in een gebouw in de omgeving hebben geplaatst
