### ISSUE TITLE
kubus fixen en 2018 maken

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/kadaster-post-processing#8]
reeds volgens afspraken 20201016, maar is kapot en ook nog 2018 doen

**Comment by joostschouppe** [comment]
Ook direct proberen:  analyse van over welke percelen we het niet zeker weten, namelijk “perceel met meerdere bewoonde woongelegenheden en minstens één inwonende eigenaar”
(dit zou moeten kunnen op basis van de bestaande kubus-script)
joost en chris bekijken dit samen

**Comment by karolienbloemen** [comment]
Alles 4 scripts op data 2018-2019-2020 opnieuw gelopen en opgeladen in beta-PinC om te testen

**Comment by joostschouppe** [comment]
Inmiddels gepubliceerd
